# Generated by Django 5.0.7 on 2024-07-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaries',
            name='author',
        ),
    ]
