# Generated by Django 5.0.7 on 2024-07-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_commentaries_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaries',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
