# Generated by Django 5.0.7 on 2024-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
