# Generated by Django 5.0.7 on 2024-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Никнейм')),
                ('image', models.ImageField(upload_to='user/', verbose_name='Фотография')),
            ],
        ),
    ]
