# Generated by Django 5.0.7 on 2024-07-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_users_name_remove_users_surname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
