# Generated by Django 5.0.7 on 2024-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_users_email_users_first_name_users_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='../static/avatar-fat.jpg', upload_to='user/avatars', verbose_name='Аватар'),
        ),
    ]
