# Generated by Django 5.0.7 on 2024-07-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_users_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
